config:
  programs:
    location: programs
  config:
    location: configs
  debian_file:
    location: deb
  history:
    location: .history
  install:
    location: install.yaml
  repository:
    app: http://127.0.1.1/store/programs/
    config: http://127.0.1.1/store/configs/
  ansible:
    vault:
      password_file: password.txt #this is password for vault
      file: vault.yml